theme: jekyll-theme-hacker
name: Web App Security Tools Comparison (WASTC)
description: Compares different web app security tools.
author: Thomas P
author_email: thomas@futuristicblanket.com
url: http://security.thomasp.me/
